spring:
  application:
    name: category-service
  profiles:
    active: ${environmentName}
management:
  endpoint:
    health:
      show-details: always

  endpoints:
    web:
      exposure:
        include: '*'


