version: "3.7"
services:
  category_service:
    build: .
    restart: always
    ports:
      - 9093:9093
    depends_on:
      - mongo_db
  mongo_db:
    image: "mongo:4.4.3"
    restart: always
    ports:
      - 27017:27017